version: '3.7'

services:
  testtemplate8.migrations:
    # image: ${DOCKER_REGISTRY-}testtemplate8sql
    env_file: .env
    build:
      context: .
      dockerfile: src/TestTemplate8.Migrations/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"